<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Spin-off of "HTML internal links"</title>
    </head>
    <style>
        body {
        background-color:rgb(207, 170, 97);
     }
     h1 {
         color:green;
     }
     p {
         color:green;
     }
     table {
         color:green;
     }
    </style>
    <body>
    
        <h1> Shelter Belt Lane Natural Meats</h1>
       
        <p> Shelter Belt Lane Natural Meat's is the place to go, were the price is low. Fresh cow meat of all types.</p>
    
        <p>
        <img src="https://cdn.arstechnica.net/wp-content/uploads/2015/04/1024px-Cow-IMG_2050-640x480.jpg" width="200">
        </p>
        
        <table>
            <thead>
                <tr>
                    <th> TYPE~~</th>
                    <th> PRICE</th>
                </tr>
            </thead>
        
       <tbody>
           <tr>
                <td>Shoulder</td>
                <td>$0.00</td>
           </tr>
            <tr>
                <td>Roast Rump</td>
                <td>$0.00</td>
           </tr>
           <tr>
                <td>Swiss</td>
                <td>$0.00</td>
           </tr>
           <tr>
                <td>Minute Steak</td>
                <td>$0.00</td>
           </tr>
           <tr>
                <td>T-Bone Steak</td>
                <td>$0.00</td>
           </tr>
           <tr>
                <td>Hambuger</td>
                <td>$0.00</td>
           </tr>
           <tr>
                <td>Rib-Eye</td>
                <td>$0.00</td>
           </tr>
           </tbody>
     </table>

    </body>
</html>
